=== degiorgioo/nitro-docker/project/src/patterns/molecules/example/schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"title": "Example",
	"description": "An Example molecule",
	"type": "object",
	"properties": {
		"modifier": {
			"description": "A modifier",
			"type": "string"
		},
		"decorator": {
			"description": "A decorator",
			"type": "string"
		},
		"title": {
			"description": "Title of the pattern",
			"type": "string",
			"minLength": 3,
			"maxLength": 100
		},
		"links": {
			"description": "An array of links",
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "object",
				"properties": {
					"uri": {
						"description": "the target uri",
						"type": "string",
						"pattern": "^[a-z]*$"
					},
					"text": {
						"description": "The link text",
						"type": "string"
					}
				}
			},
			"required": ["uri", "text"],
			"additionalProperties": false
		}
	},
	"required": ["title", "links"],
	"dependencies": {}
}

=== degiorgioo/nitro-docker/project/src/patterns/molecules/example/_data/example.json
{
	"modifier": "",
	"decorator": "",
	"title": "Example Module",
	"links": [
		{
			"uri": "index",
			"text": "Example 1"
		},
		{
			"uri": "index",
			"text": "Example 2"
		},
		{
			"uri": "index",
			"text": "Example 3"
		},
		{
			"uri": "index",
			"text": "Example 4"
		},
		{
			"uri": "index",
			"text": "Example 5"
		}
	]
}
